### ISSUE TITLE
devices/base

### ISSUE THREAD

**Issue by nespjin** [FlymeOS/devices-base#3]
devices/base目录是干什么用的，不要这个目录可不可以

**Comment by hexiaoshuai** [comment]
这是patch的基础,必须有一个基础用来patch

**Comment by nespjin** [comment]
请问一下，这个目录下的文件是不是flyme的反编译的文件

**Comment by nespjin** [comment]
flyme的源码在哪个目录？

**Comment by hexiaoshuai** [comment]
请仔细阅读https://github.com/FlymeOS/tutorials  这里有你要的答案

**Comment by nespjin** [comment]
没有源码的位置😂

**Comment by nespjin** [comment]
所谓的源码是不是反编译出来的smali
